INSERT INTO students (first_name, last_name, admission_number,student_email, phone_number, course_name)
VALUES
('Ian', 'Derrick', 1, "ian.derrick@gmail.com", 01101, 'SDF'),
('Valentine', 'Wabwire', 2, "valentine.wabwire@student.moringaschool.com", 01102, 'SDF'),
('Karl', 'Kamau', 3, "karl.kamau@student.moringaschool.com",01103, 'SDF'),
('Simon', 'Warui', 4, "simon.warui@student.moringaschool.com",01104, 'SDF'),
('Eric', 'Njuguna', 5, "eric.njuguna@student.moringaschool.com", 01105, 'SDF'),
('Johnson', 'GITHU', 6, "johnson.githu@student.moringaschool.com", 01106, 'SDF'),
('felistus', 'kimanthi', 7, "felistus.kimanthi@student.moringsschool.com", 01107, 'SDF'),
('Elizabeth', 'Gichohi', 8, "elizabeth.gichohi@student.moringaschool.com", 01108, 'SDF'),
('Moses', 'Wamuyu', 9, "moses.wamuyu@student.moringaschool.com", 01109, 'SDF'),
('Antony', 'Omondi', 10, "antony.omondi1@student.moringaschool.com", 01110, 'SDF'),
('Lucy', 'Mwangi', 11, "lucy.mwangi2@student.moringaschool.com", 01111, 'SDF'),
('Gregory', 'Kipchumba', 12, "gregory.kipchumba@student.moringaschool.com", 01112, 'SDF'),
('Dennis', 'Wanjohi', 13, "dennis.wanjohi@student.moringaschool.com", 01113, 'SDF'),
('Douglas', 'Gatimu', 14, "douglas.gatimu@student.moringaschool.com", 01114, 'SDF'),
('Anthony', 'Ngigi', 60, "anthony.ngigi@student.moringaschool.com", 01160, 'SDF'),
('CHRIS', 'JESSE', 15, "chris.jesse@student.moringaschool.com", 01115, 'SDF'),
('Elvis', 'Mbuthia', 16, "elvis.mbuthia@student.moringaschool.com", 01116, 'SDF'),
('Ellis', 'Lunayo', 17, "ellis.lunayo@student.moringaschool.com", 01117, 'SDF'), 
('ARNOLD', 'MUTAMA', 18, "arnold.mutama@student.moringaschool.com", 01118, 'SDF'),
('Antony', 'Milimo', 19, "antony.milimo@student.moringaschool.com", 01119, 'SDF'), 
('MATHIAS', 'MUNENE', 20, "mathias.munene@student.moringaschool.com", 01120, 'SDF'),
('Chege', 'Wakiama', 21, "chege.wakiama@student.moringaschool.com", 01121, 'SDF'), 
('Edith', 'Agai', 22, "edith.agai@student.moringaschool.com", 01122, 'SDF'), 
('Rowney', 'Ouma', 23, "rowney.ouma@student.moringaschool.com", 01123, 'SDF'), 
('Marion', 'Maghanga', 24, "marion.maghanga@student.moringaschool.com", 01124, 'SDF'), 
('Vallary', 'Onyando', 25, "vallary.onyando@student.moringaschool.com", 01125, 'SDF'), 
('CHRISPUS', "NG'ANG'A", 26, "chrispus.nganga@student.moringaschool.com", 01126, 'SDF'), 
('Stephen', 'Mburu', 27, "stephen.mburu1@student.moringaschool.com", 01127, 'SDF'), 
('Farouk', 'Abdi', 28, "farouk.abdi@student.moringaschool.com", 01128, 'SDF'), 
('VICTOR', 'KIRIMI', 29, "victor.kirimi@student.moringaschool.com", 01129, 'SDF'), 
('Ruth', 'Siyoi', 30, "ruth.siyoi@student.moringaschool.com", 01130, 'SDF'), 
('Faith', 'Wangari', 31, "faith.wangari@student.moringaschool.com", 01131, 'SDF'),
('Benard', 'Oluoch', 32, "benard.oluoch@student.moringaschool.com", 01132, 'SDF'), 
('Michael', 'Kariuki', 33, "michael.kariuki2@student.moringaschool.com", 01133, 'SDF'), 
('Harriet', "Chepng'eno", 34, "harriet.chepngeno@student.moringaschool.com", 01134, 'SDF'), 
('Emmah', 'Wanjiku Gicheru', 35, "emmah.gicheru@student.moringaschool.com", 01135, 'SDF'), 
('Valentine', 'Wanjiru', 36, "valentine.wanjiru@student.moringaschool.com", 01136, 'SDF'), 
('Michael', 'Luyuku', 37, "michael.luyuku@student.moringaschool.com", 01137, 'SDF'), 
('Caroline', 'Ininga', 38, "caroline.ininga@student.moringaschool.com", 01138, 'SDF'), 
('Levy', 'Mwangi', 39, "levy.mwangi@student.moringaschool.com", 01139, 'SDF'), 
('Uhuru', 'Chadwinn Uhuru', 40, "uhuru.chadwinn@student.moringaschool.com", 01140, 'SDF'), 
('Levi', 'Njogu', 41, "levi.njogu@student.moringaschool.com", 01141, 'SDF'), 
('Joseph', 'Kamau', 42, "joseph.kamau11@student.moringaschool.com", 01142, 'SDF'), 
('Moses', 'Dianga', 43, "moses.dianga@student.moringaschool.com", 01143, 'SDF'), 
('Edgar', 'Mikuro', 44, "edgar.mikuro@student.moringaschool.com", 01144, 'SDF'), 
('Ike', 'Mwthiga', 45, "ike.mwthiga@student.moringaschool.com", 01145, 'SDF'), 
('Justin', 'Kipkorir', 46, "justin.kipkorir@student.moringaschool.com", 01146, 'SDF'), 
('Collins', 'Kipkemoi', 47, "collins.kipkemoi@student.moringaschool.com", 01147, 'SDF'), 
('Brian', 'Oduory', 48, "brian.oduory@student.moringaschool.com", 01148, 'SDF'), 
('George', 'Kahuki', 49, "george.kahuki@student.moringaschool.com", 01149, 'SDF'),
('Anastasia', 'Wakoli', 50, "anastasia.wakoli@student.moringaschool.com", 01150, 'SDF'), 
('Reagan', 'Nyauma', 51, "reagan.nyauma@student.moringaschool.com", 01151, 'SDF'), 
('Paul', 'Wafula', 52, "paul.wafula2@student.moringaschool.com", 01152, 'SDF'), 
('Fatuma', 'Dahir', 53, "fatuma.dahir@student.moringaschool.com", 01153, 'SDF')